### ISSUE TITLE
client.connect((server_ip, 12306)) 执行到这里就报错了

### ISSUE THREAD

**Issue by gaawal** [itsmartkit/12306-Ticket-Booking#3]
[WinError 10061] 由于目标计算机积极拒绝，无法连接。
server_ip = cfg['server_ip']  这里的serverip是什么？

**Comment by itsmartkit** [comment]
serverip用于配置运行server.py的主机地址，该主机用于远程任务、远程日志等功能。

**Comment by gaawal** [comment]
已经部署好了，可以抢票，谢谢
