### ISSUE TITLE
请帮忙看下RAIL_DEVICEID  RAIL_EXPIRATION配置为空，执行报错是什么原因？

### ISSUE THREAD

**Issue by gaawal** [itsmartkit/12306-Ticket-Booking#4]
deviceid_key = 'RAIL_DEVICEID'
    exp_key = 'RAIL_EXPIRATION'
执行到def get_rail_deviceid():
    # 读取本地
    _device = load_obj(deviceid_cache_path)
    deviceid_key = 'RAIL_DEVICEID'
    exp_key = 'RAIL_EXPIRATION'
    if _device != None:
        if exp_key in _device:
            n = int(time.time() * 1000)
            exp = int(_device.get(exp_key))  ------------这里报错
已配置谷歌驱动文件
执行报错tails.
  cfg = yaml.load(open(cwd_path + '/config/conf.yaml','r', encoding='utf-8'))
invalid literal for int() with base 10: ''

**Comment by JiahuaLink** [comment]
RAIL_DEVICEID  RAIL_EXPIRATION 是什么意思？是否可以配置任意整型数？

**Comment by gaawal** [comment]
RAIL_DEVICEID RAIL_EXPIRATION为空就要使用驱动执行
