### ISSUE TITLE
返回参数为空, 接口状态码: 302 ，但是点击链接状态码是200

### ISSUE THREAD

**Issue by gaawal** [itsmartkit/12306-Ticket-Booking#5]
url: https://kyfw.12306.cn/otn/leftTicket/queryZ?leftTicketDTO.train_date=2020-01-09&leftTicketDTO.from_station=IOQ&leftTicketDTO.to_station=NFZ&purpose_codes=ADULT返回参数为空, 接口状态码: 302，这是为什么

**Comment by itsmartkit** [comment]
应该是没有成功获取`RAIL_DEVICEID`，302很常见，多试几次
